### ISSUE TITLE
the posting page is not responsive

### ISSUE THREAD

**Issue by icarrr** [eshlox/simplicity#10]
on the main page, it looks fine but if it is entered in posta content the page changes to be not responsive

**Comment by eshlox** [comment]
@icarrr Could you tell me more about this issue? Could you make a screenshot?

**Comment by icarrr** [comment]
@eshlox I use the simplicity theme on the hugo site, on my pc the blog page is fine but if it is opened via a smartphone it looks unresponsive.
![photo_2018-12-09_19-52-37](https://user-images.githubusercontent.com/24905668/49697587-0b957d00-fbec-11e8-8696-1d69ef0a1414.jpg)

**Comment by eshlox** [comment]
Thanks, `code` tag is not responsive. I will try to fix it this week.

**Comment by icarrr** [comment]
Nice

**Comment by eshlox** [comment]
@icarrr Fix pushed to the master branch. Could you verify it it works now?

**Comment by icarrr** [comment]
@eshlox I have tried clone, but there are still some page posts or blogs that have not been responsive.

**Comment by eshlox** [comment]
@icarrr I don't see those changes on your blog: https://github.com/eshlox/simplicity/commit/7734dfe3d05a83e42f513025fbcc82aab385a467

Are you sure that your blog is updated with the latest changes? Maybe it's cached?

**Comment by icarrr** [comment]
yes, I'm sure because I tried to make a new post but it was the same, not yet responsive in some posts. It is also not cached because I have tried cleaning the cache.

![image](https://user-images.githubusercontent.com/24905668/50038851-d9f03c00-0059-11e9-96e9-52ea5d6939bb.png)

**Comment by eshlox** [comment]
@icarrr I've added another fix for `code` element, please update the theme and test again ;-)

**Comment by icarrr** [comment]
@eshlox Nice, i have just pulled the code, and the page in question has been responsive :+1: :+1: :+1:
