### ISSUE TITLE
Incorrect .Date.Format

### ISSUE THREAD

**Issue by pjw91** [eshlox/simplicity#11]
The current time format is 12-hour clock without the AM/PM indicator, even though that field is hidden. ([layouts/_default/single.html#L5](../blob/master/layouts/_default/single.html#L5))

It would be better to use a 24-hour clock `15:04`, or a 12-hour clock with AM/PM.

**Comment by eshlox** [comment]
@pjw91 I have changed time to 24h format and added timezone.

**Comment by pjw91** [comment]
OK, thank you.
