### ISSUE TITLE
Subdirectory website

### ISSUE THREAD

**Issue by sysmso** [eshlox/simplicity#2]
Hi, 

I have a problem with your theme in my website which is in a domain subdirectory (www.example.com/hugo/) : the url are not handling properly, there is a / before all links. 
For example in the tags list : 
    
  `<div class="taxonomies">
    <h1>Tags</h1>
    <ul>
        <li>
          <a href="/tags/foreman">
            <span class="hash">#</span>foreman
          </a>
          <sup>1</sup>
        </li>`
The resulting link is www.example.com/tags/foreman instead of www.example.com/hugo/tags/foreman

How can i change this behaviour ?

Thanks for your help

**Comment by eshlox** [comment]
Hi,

Try to set `canonifyURLs` in the config file, example:

```
baseURL = "https://example.org/hugo/"
canonifyURLs = true
```

Let me know if it works for you. ;-)

**Comment by sysmso** [comment]
Ok it works with canonifyURLs thank you !
