### ISSUE TITLE
Your theme's demo is not working on the Hugo Themes website.

### ISSUE THREAD

**Issue by onedrawingperday** [eshlox/simplicity#8]
Hi @eshlox 

I saw that since commit 73a1379 your theme is using SCSS.

However you have not committed the generated resources of your theme and as a result your theme's demo [fails to generate on the Hugo website](https://themes.gohugo.io/simplicity/).

To fix this issue please have a look at the updated README of Hugo Themes: https://github.com/gohugoio/hugoThemes#resources You need to commit the `/resources/` directory and its contents in your theme's repository.

If you have any questions do not hesitate to ask me or @digitalcraftsman

**Comment by eshlox** [comment]
Hi @onedrawingperday, thanks for the information!

1. `resources` directory committed.
2. I've replaced `.Permalink` with `.RelPermalink`.

I couldn't manage to run Hugo themes site locally, I hope it works.

**Comment by onedrawingperday** [comment]
Thank you for the swift reply @eshlox 

Now when I execute the Build Script I get the following ERROR:

```
ERROR 2018/11/08 22:44:34 render of "page" failed: execute of template failed: template: _default/single.html:3:5: executing "_default/single.html" at <partial "head.html" ...>: error calling partial: "/hugoThemes/simplicity/layouts/partials/head.html:11:35": execute of template failed: template: partials/head.html:11:35: executing "partials/head.html" at <resources.Get>: error calling Get: stat /hugoThemes/simplicity/assets/node_modules/normalize.css/normalize.css: no such file or directory
FAILED to create exampleSite for simplicity
```
It seems that `/assets/node_modules/normalize.css/normalize.css` is not included in your theme's repository.

Please look into the above and let me know.

Thanks!

**Comment by eshlox** [comment]
@onedrawingperday It should work now, I hope so ;-)

**Comment by digitalcraftsman** [comment]
Thanks @eshlox for fixing the issues. I've updated all themes and the simplicity theme is running fine again: https://themes.gohugo.io/simplicity/. Hence this issue can be closed.

**Comment by onedrawingperday** [comment]
Thanks for making the changes @eshlox
